### PR TITLE
revamped trade UI

### PR DESCRIPTION
**Pull request by dcposch**
## Before

image

## After

image

https://user-images.githubusercontent.com/169280/183263780-f77f03d9-ce80-4111-b68d-38359db7ea8d.mov

### CODE REVIEW

**Comment by kahuang** [comment]
Looking excellent!

I assume market buy/sells will be a straightforward extension from here?

**Comment by dcposch** [comment]
## Working end-to-end

image

image

image

image

image

**Comment by dcposch** [comment]
## Approval flow

image

image

**Comment by dcposch** [comment]
## Mobile

image

**Pull request merged**
